// DataView.jsx — browse every data/analysis CSV as an interactive table + column
// stats + a simple inline-SVG chart (histogram for numeric, bar for categorical).
import React, { useMemo, useState } from 'react'
import { parseCSV, profile } from './csv.js'

function Bars({ labels, values, color = '#4f46e5' }) {
  const max = Math.max(1, ...values)
  const W = 460, H = 200, pad = 28, bw = (W - pad) / values.length
  return (
    <svg className="chart" viewBox={`0 0 ${W} ${H + 24}`} width="100%">
      {values.map((v, i) => {
        const h = (v / max) * H
        return (
          <g key={i}>
            <rect x={pad + i * bw + 2} y={H - h} width={Math.max(1, bw - 4)} height={h} fill={color} rx="2" />
            <text x={pad + i * bw + bw / 2} y={H + 14} fontSize="8" textAnchor="middle" fill="currentColor"
                  transform={labels.length > 8 ? `rotate(35 ${pad + i * bw + bw / 2} ${H + 14})` : ''}>
              {String(labels[i]).slice(0, 10)}
            </text>
          </g>
        )
      })}
      <text x={pad} y={12} fontSize="9" fill="currentColor">max {max}</text>
    </svg>
  )
}

function Chart({ col, rows }) {
  if (!col) return null
  if (col.numeric) {
    const nums = rows.map((r) => Number(r[col.name])).filter((n) => !Number.isNaN(n))
    const bins = 10, lo = col.min, hi = col.max, w = (hi - lo) / bins || 1
    const counts = new Array(bins).fill(0)
    for (const n of nums) counts[Math.min(bins - 1, Math.floor((n - lo) / w))]++
    const labels = counts.map((_, i) => (lo + i * w).toFixed(1))
    return <Bars labels={labels} values={counts} />
  }
  return <Bars labels={col.top.map((t) => t[0])} values={col.top.map((t) => t[1])} color="#0ea5e9" />
}

export default function DataView({ datasets }) {
  const [active, setActive] = useState(datasets[0]?.name)
  const ds = datasets.find((d) => d.name === active) || datasets[0]
  const { headers, rows } = useMemo(() => parseCSV(ds.text), [ds])
  const cols = useMemo(() => profile(headers, rows), [headers, rows])
  const [chartCol, setChartCol] = useState(null)
  const activeCol = cols.find((c) => c.name === chartCol) || cols.find((c) => c.numeric) || cols[0]

  return (
    <div className="shell">
      <aside className="sidebar">
        <div className="brand">Datasets<small>data/analysis/*.csv — generated by the pipelines</small></div>
        {datasets.map((d) => (
          <button key={d.name} className={'navitem' + (d.name === ds.name ? ' active' : '')}
                  onClick={() => { setActive(d.name); setChartCol(null) }}>
            {d.name}
          </button>
        ))}
        <div className="count">{datasets.length} datasets</div>
      </aside>
      <main className="content">
        <div className="crumb">Data · {ds.name} · {rows.length} rows × {headers.length} cols</div>
        <h1 className="md-inline-h1">{ds.name}</h1>

        <h2 className="dash-h2">Chart</h2>
        <select className="search" style={{ maxWidth: 320 }} value={activeCol?.name}
                onChange={(e) => setChartCol(e.target.value)}>
          {cols.map((c) => <option key={c.name} value={c.name}>{c.name} ({c.numeric ? 'numeric' : 'categorical'})</option>)}
        </select>
        <div className="chartbox"><Chart col={activeCol} rows={rows} /></div>

        <h2 className="dash-h2">Column summary</h2>
        <table className="dash">
          <thead><tr><th>Column</th><th>Type</th><th>Missing</th><th>Min / Top</th><th>Max / Unique</th><th>Mean</th></tr></thead>
          <tbody>
            {cols.map((c) => (
              <tr key={c.name}>
                <td>{c.name}</td>
                <td>{c.numeric ? 'numeric' : 'categorical'}</td>
                <td>{c.missing}</td>
                <td>{c.numeric ? c.min : (c.top?.[0]?.[0] ?? '')}</td>
                <td>{c.numeric ? c.max : c.unique}</td>
                <td>{c.numeric ? c.mean.toFixed(2) : ''}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <h2 className="dash-h2">Rows (first 100)</h2>
        <div style={{ overflowX: 'auto' }}>
          <table className="dash">
            <thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead>
            <tbody>
              {rows.slice(0, 100).map((r, i) => (
                <tr key={i}>{headers.map((h) => <td key={h}>{r[h]}</td>)}</tr>
              ))}
            </tbody>
          </table>
        </div>
      </main>
    </div>
  )
}
